### ISSUE TITLE
No package available for Python 3.11 on pypi

### ISSUE THREAD

**Issue by zenmonkeykstop** [digicert/onionmaker#5]
We use onionmaker on Tails to generate CSRs for onion services. Tails recently updated to Tails 6, which is based on debian bookworm and ships with Python 3.11. 

The latest binary package available for onionmaker is for 3.10 - it would be cool to have a verified binary for 3.11 as well, to eliminate the need to compile from scratch.

Update: also, installing from source via pip fails due to the issue in #4

**Comment by CBonnell** [comment]
Hi @zenmonkeykstop, thanks for filing this. Thanks to @cfm's contribution in #6, the project should now be able to be built from source. Additionally, I updated the CI/CD tooling and cut a new release, so wheels for newer versions of Python are now available on PyPi.

**Comment by zenmonkeykstop** [comment]
Much appreciated, thanks!
